---
when:
  - event: push
    branch: main
  - event: pull_request
    branch: main

steps:
  - name: lint
    image: golangci/golangci-lint:v2.11.4
    commands:
      - golangci-lint run ./...

  - name: helm-lint
    image: alpine/helm:3.17.3
    commands:
      - helm lint charts/pangolin-operator
