---
when:
  - event: push
    branch: main
  - event: pull_request
    branch: main

steps:
  - name: lint
    image: golangci/golangci-lint:v2.11.4
    commands:
      - golangci-lint run ./...

  - name: helm-lint
    image: alpine/helm:4.1.4
    commands:
      - helm lint charts/pangolin-operator

  - name: helm-unittest
    image: helmunittest/helm-unittest:4.1.3-0.8.2
    commands:
      - helm unittest charts/pangolin-operator
